[package]
name = "server-impl"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
axum = { version = "0.8.1", features = ["ws"] }
tracing = "0.1"
futures = "0.3"
tower = "0.5.2"
